### ISSUE TITLE
Envío a sensores

### ISSUE THREAD

**Issue by cmmata** [jalucenyo/Dhome#1]

**Comment by jalucenyo** [comment]
Implementado el envio de mensajes en JSON a los sensores, para poder realizar acciones.
Tambien se incorpora el concepto de attributos en el WeaconNode, se compone de un HashMap (Calve, Valor) con los atributos que puede tener cada Weacon.

Por ejemplo, el Weacon ambiental tiene los atributos "temp" y "humidity", el Weacon de control de la tira de leds tiene el "brightness" brillo. Los tipos y atributos podemos verlos en la clase WeaconHelper.
